[package]
name    = "BSP-Strom-Mapa"
version = "0.2.0"
edition = "2021"

[dependencies]
anyhow          = "1"
cgmath          = "0.18"
egui            = "0.29"
three-d         = { version = "0.18", features = ["window", "egui-gui"] }
three-d-asset   = "0.9"